parking_system/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('system.urls')),
]

system/urls.py
from django.urls import path
from . import views
from .views import login_view

urlpatterns = [
    path('', login_view, name='login'), 
    path('home/', views.home, name='home'),
    path('vehicle_management/',views.vehicle_management,name='vehicle_management'),
    path('parking_status/',views.parking_status,name='parking_status'),
    path('vehicle_report/', views.vehicle_report, name='vehicle_report'),
    path('register/', views.register, name='register'),
    path('home/employee_management/', views.employee_management, name='employee_management'),
    path('employee/delete/<str:nhanvienid>/', views.delete_employee, name='delete_employee'),
    path('employee-management/', views.employee_management, name='employee_management'),
    path('employee_management/', views.employee_management, name='employee_management'),
    path('add_employee/', views.add_employee, name='add_employee'),
    path('nhanvien/', views.employee_management, name='employee_management'),
    path('nhanvien/sua/<str:nhanvienid>/', views.edit_employee, name='edit_employee'),
    path('nhanvien/xoa/<str:nhanvienid>/', views.delete_employee, name='delete_employee'),
    path('nhanvien/them/', views.add_employee, name='add_employee'),
    path('search/', views.search_employee, name='search_employee'),
    path('vehicles/', views.vehicle_management, name='vehicle_management'),  # Trang danh sách xe
    path('vehicle/edit/<str:pk>/', views.vehicle_edit, name='vehicle_edit'),  # Trang sửa xe
    path('vehicle/delete/<str:pk>/', views.vehicle_delete, name='vehicle_delete'),  # Trang xóa xe
    path('vehicle_report/export/', views.export_vehicle_report, name='export_vehicle_report'),  # Xuất báo cáo xe
]

system/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Giave(models.Model):
    magia = models.AutoField(db_column='MaGia', primary_key=True)  # Field name made lowercase.
    loaixe = models.CharField(db_column='LoaiXe', unique=True, max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')  # Field name made lowercase.
    giatheogio = models.DecimalField(db_column='GiaTheoGio', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'GiaVe'


class Hoadon(models.Model):
    mahd = models.AutoField(db_column='MaHD', primary_key=True)  # Field name made lowercase.
    maluot = models.ForeignKey('Luotravao', models.DO_NOTHING, db_column='MaLuot')  # Field name made lowercase.
    ngaylap = models.DateTimeField(db_column='NgayLap', blank=True, null=True)  # Field name made lowercase.
    sogiogui = models.IntegerField(db_column='SoGioGui')  # Field name made lowercase.
    tongtien = models.DecimalField(db_column='TongTien', max_digits=10, decimal_places=2, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'HoaDon'


class Khachhang(models.Model):
    makh = models.AutoField(db_column='MaKH', primary_key=True)  # Field name made lowercase.
    hoten = models.CharField(db_column='HoTen', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    sodienthoai = models.CharField(db_column='SoDienThoai', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ghichu = models.CharField(db_column='GhiChu', max_length=255, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'KhachHang'


class Nhanvien(models.Model):
    nhanvienid = models.CharField(db_column='NhanVienID', primary_key=True, max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')  # Field name made lowercase.
    hoten = models.CharField(db_column='HoTen', max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    diachi = models.CharField(db_column='DiaChi', max_length=200, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    sodienthoai = models.CharField(db_column='SoDienThoai', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    ngaysinh = models.DateTimeField(db_column='NgaySinh', blank=True, null=True)  # Field name made lowercase.
    chucvu = models.CharField(db_column='ChucVu', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    phanquyen=models.CharField(db_column='Phanquyen', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    email=models.CharField(db_column='Email', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    matkhau=models.CharField(db_column='MatKhau', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    
    class Meta:
        managed = False
        db_table = 'NhanVien'



class Luotravao(models.Model):
    maluot = models.AutoField(db_column='MaLuot', primary_key=True)  # Field name made lowercase.
    bienso = models.ForeignKey('Xe', models.DO_NOTHING, db_column='BienSo')  # Field name made lowercase.
    thoigianvao = models.DateTimeField(db_column='ThoiGianVao')  # Field name made lowercase.
    thoigianra = models.DateTimeField(db_column='ThoiGianRa', blank=True, null=True)  # Field name made lowercase.
    anhvao = models.CharField(db_column='AnhVao', max_length=255, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    anhra = models.CharField(db_column='AnhRa', max_length=255, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    mavitri = models.ForeignKey('Vitridoxe', models.DO_NOTHING, db_column='MaViTri', blank=True, null=True)  # Field name made lowercase.
    trangthai = models.CharField(db_column='TrangThai', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'LuotRaVao'


class Vitridoxe(models.Model):
    mavitri = models.AutoField(db_column='MaViTri', primary_key=True)  # Field name made lowercase.
    tenvitri = models.CharField(db_column='TenViTri', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS')  # Field name made lowercase.
    trangthai = models.CharField(db_column='TrangThai', max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'ViTriDoXe'


class Xe(models.Model):
    bienso = models.CharField(db_column='BienSo', primary_key=True, max_length=20, db_collation='SQL_Latin1_General_CP1_CI_AS')  # Field name made lowercase.
    loaixe = models.CharField(db_column='LoaiXe', max_length=50, db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)  # Field name made lowercase.
    makh = models.ForeignKey(Khachhang, models.DO_NOTHING, db_column='MaKH', blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'Xe'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150, db_collation='SQL_Latin1_General_CP1_CI_AS')

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255, db_collation='SQL_Latin1_General_CP1_CI_AS')
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128, db_collation='SQL_Latin1_General_CP1_CI_AS')
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.BooleanField()
    username = models.CharField(unique=True, max_length=150, db_collation='SQL_Latin1_General_CP1_CI_AS')
    first_name = models.CharField(max_length=150, db_collation='SQL_Latin1_General_CP1_CI_AS')
    last_name = models.CharField(max_length=150, db_collation='SQL_Latin1_General_CP1_CI_AS')
    email = models.CharField(max_length=254, db_collation='SQL_Latin1_General_CP1_CI_AS')
    is_staff = models.BooleanField()
    is_active = models.BooleanField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS', blank=True, null=True)
    object_repr = models.CharField(max_length=200, db_collation='SQL_Latin1_General_CP1_CI_AS')
    action_flag = models.SmallIntegerField()
    change_message = models.TextField(db_collation='SQL_Latin1_General_CP1_CI_AS')
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')
    model = models.CharField(max_length=100, db_collation='SQL_Latin1_General_CP1_CI_AS')

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    id = models.BigAutoField(primary_key=True)
    app = models.CharField(max_length=255, db_collation='SQL_Latin1_General_CP1_CI_AS')
    name = models.CharField(max_length=255, db_collation='SQL_Latin1_General_CP1_CI_AS')
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):

system/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Quản lý Nhân viên & Quyền truy cập</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <link href="{% static 'app/css/base.css' %}" rel="stylesheet" />
</head>

<body class="bg-gray-50">
    <div class="wrapper">
        <!-- Navigation -->
        <nav class="navbar-custom fixed top-0 left-0 right-0 z-50 bg-white shadow-md">
            <div class="container mx-auto px-4 sm:px-6 flex justify-between items-center py-4">
                <a class="navbar-brand text-xl font-semibold text-blue-600" href="{% url 'home' %}">Quản lý Bãi giữ xe</a>
                <div class="hidden sm:flex sm:items-center sm:space-x-4" id="navbarMenu">
                    <a class="nav-link text-gray-800 hover:text-blue-600" href="{% url 'vehicle_management' %}">Quản lý xe</a>
                    <a class="nav-link text-gray-800 hover:text-blue-600" href="{% url 'parking_status' %}">Tình trạng bãi xe</a>
                    <a class="nav-link text-gray-800 hover:text-blue-600" href="{% url 'vehicle_report' %}">Báo cáo & thống kê</a>
                    <a class="nav-link text-gray-800 hover:text-blue-600" href="{% url 'employee_management' %}">Quản lý nhân viên</a>
                    <a class="logout text-gray-800 hover:text-blue-600" href="{% url 'login' %}">Đăng xuất</a>
                </div>

                <!-- User Info - "Xin chào" display at top right -->
                <div class="absolute top-4 right-4 text-right">
                    <p class="text-sm text-gray-600">Xin chào, <span class="font-semibold text-blue-600">{{ user.username }}</span></p>
                    {% if user.last_name == "Quản lý Nhân Viên" %}
                        <p class="text-xs text-green-500">Quản lý nhân viên</p>
                    {% elif user.last_name == "Nhân viên thống Kê báo cáo" %}
                        <p class="text-xs text-yellow-500">NV thống Kê báo cáo</p>
                    {% elif user.last_name == "Nhân viên xe ra vào" %}
                        <p class="text-xs text-blue-500"> Nhân viên Quản lý xe </p>
                    {% elif user.last_name == "Quản lý bãi xe" %}
                        <p class="text-xs text-purple-500">Nhân viên Quản lý bãi xe</p>
                    {% else %}
                        <p class="text-xs text-gray-400">Nhân viên</p>
                    {% endif %}
                </div>
            </div>
        </nav>

        <!-- Main Content -->
        <main style="padding-top: 80px">
            {% block contents %}
            <!-- Content goes here -->
            {% endblock contents %}
        </main>

        <!-- Footer -->
        <footer class="footer">
            <div class="footer-container">
                <div class="footer-main">
                    <div class="footer-info">
                        <h3>Hệ thống quản lý bãi giữ xe</h3>
                        <p>Giải pháp quản lý bãi đỗ xe thông minh, tiện lợi và an toàn.</p>
                        <div class="contact-info">
                            <div class="contact-item">
                                <i class="fas fa-map-marker-alt"></i>
                                <span>123 Nguyễn Văn A, Q.1, TP.HCM</span>
                            </div>
                            <div class="contact-item">
                                <i class="fas fa-phone-alt"></i>
                                <span>0987 654 321</span>
                            </div>
                            <div class="contact-item">
                                <i class="fas fa-envelope"></i>
                                <span>support@baigiu.com</span>
                            </div>
                        </div>
                    </div>
                    <div class="footer-links">
                        <div class="link-group">
                            <h4>Dịch vụ</h4>
                            <ul>
                                <li><a href="#">Quản lý bãi giữ xe</a></li>
                                <li><a href="#">Đặt chỗ trước</a></li>
                                <li><a href="#">Báo cáo thống kê</a></li>
                            </ul>
                        </div>
                        <div class="link-group">
                            <h4>Hỗ trợ</h4>
                            <ul>
                                <li><a href="#">Hướng dẫn sử dụng</a></li>
                                <li><a href="#">Câu hỏi thường gặp</a></li>
                                <li><a href="#">Điều khoản dịch vụ</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="social-newsletter">
                        <div class="social-media">
                            <h4>Kết nối với chúng tôi</h4>
                            <div class="social-icons">
                                <a href="#" class="icon-facebook"><i class="fab fa-facebook-f"></i></a>
                                <a href="#" class="icon-twitter"><i class="fab fa-twitter"></i></a>
                                <a href="#" class="icon-youtube"><i class="fab fa-youtube"></i></a>
                                <a href="#" class="icon-linkedin"><i class="fab fa-linkedin-in"></i></a>
                            </div>
                        </div>
                        <div class="newsletter">
                            <h4>Đăng ký nhận tin</h4>
                            <p>Nhận thông báo về tính năng mới và cập nhật hệ thống.</p>
                            <div class="newsletter-form">
                                <input type="email" placeholder="Email của bạn">
                                <button type="submit"><i class="fas fa-paper-plane"></i></button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="footer-bottom">
                    <p>© 2025 Quản lý bãi giữ xe. Tất cả quyền được bảo lưu.</p>
                </div>
            </div>
        </footer>
    </div>
</body>
</html>

system/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static 'app/css/login.css' %}" rel="stylesheet" />
    <title>Login Form</title>
  </head>
  <body>
    <div class="login-container">
      <h2>LOGIN</h2>

      <form method="post">
        {% csrf_token %}
        
        <!-- Nhập email hoặc tên đăng nhập -->
        <div class="input-group">
          <input
            type="text"
            name="tendangnhap"
            placeholder="Email or Username"
            required
            autofocus
          />
        </div>

        <!-- Nhập mật khẩu -->
        <div class="input-group">
          <input
            type="password"
            name="matkhau"
            placeholder="Password"
            required
          />
        </div>

        <button type="submit" class="login-btn">LOGIN</button>
      </form>



      <!-- Hiển thị lỗi nếu có -->
      {% if error %}
        <p style="color: red; margin-top: 10px;">{{ error }}</p>
      {% endif %}
    </div>

    <footer>© 2025 Quản lý bãi giữ xe. Tất cả quyền được bảo lưu</footer>
  </body>
</html>

system/templates/vehicle_confirm_delete.html
{% extends "base.html" %}
{% load static %}

{% block contents %}
<div class="max-w-lg mx-auto mt-20 bg-white rounded-xl shadow-lg p-8">
  <h1 class="text-3xl font-bold text-center mb-6 text-red-600">Xác nhận xóa xe</h1>
  <p class="text-lg text-center mb-8">Bạn có chắc chắn muốn xóa xe có biển số <span class="font-semibold text-blue-700">"{{ vehicle.bienso }}"</span>?</p>
  <form method="POST" class="flex flex-col sm:flex-row justify-center gap-4">
    {% csrf_token %}
    <button type="submit" class="bg-red-600 text-white font-semibold rounded-lg px-8 py-2 hover:bg-red-700 transition shadow">Xóa</button>
    <a href="{% url 'vehicle_management' %}" class="bg-gray-200 text-gray-800 font-semibold rounded-lg px-8 py-2 hover:bg-gray-300 transition shadow text-center">Hủy</a>
  </form>
</div>
{% endblock %}

system/templates/vehicle_edit.html
{% extends "base.html" %}
{% load static %}

{% block contents %}
<div class="max-w-lg mx-auto mt-10 bg-white rounded-xl shadow-lg p-8">
  <h1 class="text-3xl font-bold text-center mb-8 text-blue-700">Sửa thông tin xe</h1>
  <form method="POST" class="space-y-6">
    {% csrf_token %}
    <div>
      <label class="block text-sm font-semibold mb-2">Biển số</label>
      <input type="text" name="bienso" value="{{ vehicle.bienso }}" required class="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none">
    </div>
    <div>
      <label class="block text-sm font-semibold mb-2">Loại xe</label>
      <input type="text" name="loaixe" value="{{ vehicle.loaixe }}" required class="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none">
    </div>
    <div>
      <label class="block text-sm font-semibold mb-2">Mã khách hàng (nếu có)</label>
      <input type="text" name="makh" value="{{ vehicle.makh.id }}" class="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500 focus:outline-none">
    </div>
    <div class="flex justify-center">
      <button type="submit" class="bg-blue-600 text-white font-semibold rounded-lg px-8 py-2 hover:bg-blue-700 transition shadow">Lưu</button>
    </div>
  </form>
</div>
{% endblock %}

system/templates/vehicle_management.html
{% extends "base.html" %}
{% load static %}
{% load humanize %}
{% block contents %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Quản lý xe ra vào</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static 'app/css/vehicle_management.css' %}" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />
  </head>

  <body>
    <main class="container mx-auto p-4 sm:p-6 max-w-6xl mt-20">
      <header class="text-center mb-8">
        <h1 class="text-3xl sm:text-4xl font-bold text-gray-800">Danh sách xe trong hệ thống</h1>
      </header>
      <h1>chỉ nhân viên quản lý xe ra vào   được tùy chỉnh </h1>
      <!-- Tìm kiếm -->
      <div class="mb-6 flex justify-center">
        <input
          type="text"
          id="searchInput"
          class="border border-gray-300 rounded-xl p-2 w-full max-w-md focus:ring-2 focus:ring-blue-500 focus:outline-none"
          placeholder="Tìm kiếm theo biển số, loại xe, chủ xe..."
          onkeyup="searchVehicle()"
        />
      </div>

      <!-- Xe còn đang ở bãi -->
      <div class="bg-white p-6 rounded-2xl shadow-lg mb-10">
        <h2 class="text-2xl font-semibold mb-4 text-green-600">Xe đang gửi trong bãi</h2>
        <div class="overflow-auto">
          <table class="table-auto w-full text-sm" id="vehicleTableIn">
            <thead class="bg-gray-200">
              <tr>
                <th class="px-4 py-2 text-left">Biển số</th>
                <th class="px-4 py-2 text-left">Loại xe</th>
                <th class="px-4 py-2 text-left">Chủ xe</th>
                <th class="px-4 py-2 text-left">Vị trí</th>
                <th class="px-4 py-2 text-left">Thời gian vào</th>
                <th class="px-4 py-2 text-left">Hành động</th>
              </tr>
            </thead>
            <tbody>
              {% for item in vehicles %}
                {% for luot in item.vehicle.luotravao_set.all %}
                  {% if not luot.thoigianra %}
                    <tr class="border-b">
                      <td class="px-4 py-2">{{ item.vehicle.bienso }}</td>
                      <td class="px-4 py-2">{{ item.vehicle.loaixe }}</td>
                      <td class="px-4 py-2">
                        {% if item.vehicle.makh %}
                          {{ item.vehicle.makh.ten }}
                        {% else %}
                          Chưa có chủ xe
                        {% endif %}
                      </td>
                      <td class="px-4 py-2">{{ item.ten_vitri }}</td>
                      <td class="px-4 py-2">{{ luot.thoigianvao|date:"d/m/Y H:i" }}</td>
                      <td class="px-4 py-2">
                        <a href="{% url 'vehicle_edit' item.vehicle.bienso %}" class="text-blue-500">Sửa</a> |
                        <a href="{% url 'vehicle_delete' item.vehicle.bienso %}" class="text-red-500">Xóa</a>
                      </td>
                    </tr>
                  {% endif %}
                {% endfor %}
              {% empty %}
                <tr>
                  <td colspan="6" class="text-center py-2">Không có xe nào đang gửi trong bãi</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>

      <!-- Xe đã ra khỏi bãi -->
      <div class="bg-white p-6 rounded-2xl shadow-lg">
        <h2 class="text-2xl font-semibold mb-4 text-blue-600">Xe đã rời khỏi bãi</h2>
        <div class="overflow-auto">
          <table class="table-auto w-full text-sm" id="vehicleTableOut">
            <thead class="bg-gray-200">
              <tr>
                <th class="px-4 py-2 text-left">Biển số</th>
                <th class="px-4 py-2 text-left">Loại xe</th>
                <th class="px-4 py-2 text-left">Chủ xe</th>
                <th class="px-4 py-2 text-left">Vị trí</th>
                <th class="px-4 py-2 text-left">Thời gian vào</th>
                <th class="px-4 py-2 text-left">Thời gian ra</th>
                <th class="px-4 py-2 text-left">Tổng tiền</th>
                <th class="px-4 py-2 text-left">Hành động</th>
              </tr>
            </thead>
            <tbody>
              {% for item in vehicles %}
                {% for wrapped in item.luots %}
                    {% with luot=wrapped.luot tong_tien=wrapped.tong_tien %}
                    
                    {% if luot.thoigianra %}
                        <tr class="border-b">
                          <td class="px-4 py-2">{{ item.vehicle.bienso }}</td>
                          <td class="px-4 py-2">{{ item.vehicle.loaixe }}</td>
                          <td class="px-4 py-2">
                            {% if item.vehicle.makh %}
                              {{ item.vehicle.makh.ten }}
                            {% else %}
                              Chưa có chủ xe
                            {% endif %}
                          </td>
                          <td class="px-4 py-2">{{ item.ten_vitri }}</td>
                          <td class="px-4 py-2">{{ luot.thoigianvao|date:"d/m/Y H:i" }}</td>
                          <td class="px-4 py-2">{{ luot.thoigianra|date:"d/m/Y H:i" }}</td>
                          <td class="px-4 py-2">{{ tong_tien|intcomma }} VND</td>
                          <td class="px-4 py-2">
                            <a href="{% url 'vehicle_edit' item.vehicle.bienso %}" class="text-blue-500">Sửa</a> |
                            <a href="{% url 'vehicle_delete' item.vehicle.bienso %}" class="text-red-500">Xóa</a>
                          </td>
                        </tr>
                    {% endif %}
                    
                    {% endwith %}
                {% endfor %}
            {% empty %}
            <tr>
              <td colspan="8" class="text-center py-2">Không có xe nào đã ra khỏi bãi</td>
            </tr>
            {% endfor %}

            </tbody>
          </table>
        </div>
      </div>

    </main>

    <!-- Script tìm kiếm -->
    <script>
      function searchVehicle() {
        const input = document.getElementById("searchInput").value.toLowerCase();
        const tables = ["vehicleTableIn", "vehicleTableOut"];

        tables.forEach(function(tableId) {
          const table = document.getElementById(tableId);
          const trs = table.getElementsByTagName("tr");

          for (let i = 1; i < trs.length; i++) { // bỏ header
            const tds = trs[i].getElementsByTagName("td");
            let found = false;
            for (let j = 0; j < tds.length - 1; j++) { // trừ cột Hành động
              if (tds[j] && tds[j].textContent.toLowerCase().includes(input)) {
                found = true;
                break;
              }
            }
            trs[i].style.display = found ? "" : "none";
          }
        });
      }
    </script>

  </body>
</html>
{% endblock contents %}